// <auto-generated />
using System;
using GolfViewApartments.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GolfViewApartments.API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260218133443_UpdatedAmenitiesSectionAndPrices")]
    partial class UpdatedAmenitiesSectionAndPrices
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("GolfViewApartments.API.Models.Admin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Admins");
                });

            modelBuilder.Entity("GolfViewApartments.API.Models.AmenityPricing", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("IconClass")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("AmenityPricing");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IconClass = "fa-solid fa-dumbbell",
                            Name = "Gym Access",
                            Price = 500m,
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 2,
                            IconClass = "fa-solid fa-person-swimming",
                            Name = "Pool Access",
                            Price = 500m,
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 3,
                            IconClass = "fa-solid fa-hot-tub-person",
                            Name = "Steam Bath",
                            Price = 1000m,
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 4,
                            IconClass = "fa-solid fa-fire",
                            Name = "Sauna",
                            Price = 1000m,
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("GolfViewApartments.API.Models.Apartment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ApartmentId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("DailyBB")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("DailyBedOnly")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("MaxGuests")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("MonthlyBB")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MonthlyBedOnly")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Size")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalUnits")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Apartments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ApartmentId = "studio-apartment",
                            DailyBB = 0m,
                            DailyBedOnly = 0m,
                            MaxGuests = 2,
                            MonthlyBB = 0m,
                            MonthlyBedOnly = 0m,
                            Name = "Studio Apartment",
                            Size = "24 sqm",
                            TotalUnits = 13,
                            Type = "studio"
                        },
                        new
                        {
                            Id = 2,
                            ApartmentId = "one-bedroom-apartment",
                            DailyBB = 0m,
                            DailyBedOnly = 0m,
                            MaxGuests = 2,
                            MonthlyBB = 0m,
                            MonthlyBedOnly = 0m,
                            Name = "One Bedroom Apartment",
                            Size = "30 sqm",
                            TotalUnits = 13,
                            Type = "one-bedroom"
                        },
                        new
                        {
                            Id = 3,
                            ApartmentId = "two-bedroom-apartment",
                            DailyBB = 0m,
                            DailyBedOnly = 0m,
                            MaxGuests = 4,
                            MonthlyBB = 0m,
                            MonthlyBedOnly = 0m,
                            Name = "Two Bedroom Apartment",
                            Size = "40 sqm",
                            TotalUnits = 13,
                            Type = "two-bedroom"
                        });
                });

            modelBuilder.Entity("GolfViewApartments.API.Models.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Adults")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ApartmentId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("BoardType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("BookingReference")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CheckIn")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CheckOut")
                        .HasColumnType("TEXT");

                    b.Property<int>("Children")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ChildrenAges")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("CustomerId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Occupancy")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Room")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("RoomType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("SpecialRequests")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BookingReference")
                        .IsUnique()
                        .HasDatabaseName("IX_Bookings_BookingReference");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_Bookings_CreatedAt");

                    b.HasIndex("CustomerId")
                        .HasDatabaseName("IX_Bookings_CustomerId");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_Bookings_Status");

                    b.HasIndex("ApartmentId", "CheckIn", "CheckOut")
                        .HasDatabaseName("IX_Bookings_Apartment_Dates");

                    b.HasIndex("Room", "CheckIn", "CheckOut")
                        .HasDatabaseName("IX_Bookings_Room_Dates");

                    b.HasIndex("RoomType", "CheckIn", "CheckOut")
                        .HasDatabaseName("IX_Bookings_RoomType_Dates");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("GolfViewApartments.API.Models.ConferencePackage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("IconClass")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ConferencePackages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IconClass = "fa-solid fa-sun",
                            Name = "Full Day Package",
                            Price = 2500m
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IconClass = "fa-solid fa-cloud-sun",
                            Name = "Half Day Package",
                            Price = 1500m
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IconClass = "fa-solid fa-bed-pulse",
                            Name = "Residential Package",
                            Price = 8000m
                        });
                });

            modelBuilder.Entity("GolfViewApartments.API.Models.ContactInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("FacebookUrl")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("InstagramUrl")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("TwitterUrl")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Website")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("WhatsApp")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ContactInfo");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Muchai Drive, off Ngong Road, Nairobi, Kenya",
                            Description = "Nestled in the quiet and tranquil Muchai drive off Ngong Road, Golfview provides secure first-class accommodation second to none!",
                            Email = "info@golfviewapartments.co.ke",
                            FacebookUrl = "",
                            InstagramUrl = "",
                            Phone = "+254 700 000 000",
                            TwitterUrl = "",
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Website = "https://golfviewapartments.co.ke",
                            WhatsApp = "+254 700 000 000"
                        });
                });

            modelBuilder.Entity("GolfViewApartments.API.Models.ContactMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsRead")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ContactMessages");
                });

            modelBuilder.Entity("GolfViewApartments.API.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("GolfViewApartments.API.Models.FitnessAmenity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("DayRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("IconClass")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("MonthlyRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("FitnessAmenities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DayRate = 500m,
                            IconClass = "fa-solid fa-dumbbell",
                            MonthlyRate = 5000m,
                            Name = "Gym Only"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DayRate = 500m,
                            IconClass = "fa-solid fa-dumbbell",
                            MonthlyRate = 5000m,
                            Name = "Gym and Pool"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DayRate = 1000m,
                            IconClass = "fa-solid fa-water",
                            MonthlyRate = 0m,
                            Name = "Steam and Sauna"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DayRate = 500m,
                            IconClass = "fa-solid fa-person-swimming",
                            MonthlyRate = 5000m,
                            Name = "Pool, Steam and Sauna"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DayRate = 1000m,
                            IconClass = "fa-solid fa-hot-tub-person",
                            MonthlyRate = 5000m,
                            Name = "Gym, Pool, Steam and Sauna"
                        });
                });

            modelBuilder.Entity("GolfViewApartments.API.Models.Photo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Photos");
                });

            modelBuilder.Entity("GolfViewApartments.API.Models.Room", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ApartmentId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Floor")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ApartmentId");

                    b.ToTable("Rooms");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ApartmentId = 1,
                            Floor = 0,
                            IsAvailable = true,
                            Number = "G01",
                            Type = "Studio"
                        },
                        new
                        {
                            Id = 2,
                            ApartmentId = 2,
                            Floor = 0,
                            IsAvailable = true,
                            Number = "G02",
                            Type = "1 Bedroom"
                        },
                        new
                        {
                            Id = 3,
                            ApartmentId = 3,
                            Floor = 0,
                            IsAvailable = true,
                            Number = "G03",
                            Type = "2 Bedroom"
                        },
                        new
                        {
                            Id = 4,
                            ApartmentId = 1,
                            Floor = 1,
                            IsAvailable = true,
                            Number = "101",
                            Type = "Studio"
                        },
                        new
                        {
                            Id = 5,
                            ApartmentId = 2,
                            Floor = 1,
                            IsAvailable = true,
                            Number = "102",
                            Type = "1 Bedroom"
                        },
                        new
                        {
                            Id = 6,
                            ApartmentId = 3,
                            Floor = 1,
                            IsAvailable = true,
                            Number = "103",
                            Type = "2 Bedroom"
                        },
                        new
                        {
                            Id = 7,
                            ApartmentId = 1,
                            Floor = 1,
                            IsAvailable = true,
                            Number = "104",
                            Type = "Studio"
                        },
                        new
                        {
                            Id = 8,
                            ApartmentId = 2,
                            Floor = 1,
                            IsAvailable = true,
                            Number = "105",
                            Type = "1 Bedroom"
                        },
                        new
                        {
                            Id = 9,
                            ApartmentId = 3,
                            Floor = 1,
                            IsAvailable = true,
                            Number = "106",
                            Type = "2 Bedroom"
                        },
                        new
                        {
                            Id = 10,
                            ApartmentId = 1,
                            Floor = 2,
                            IsAvailable = true,
                            Number = "201",
                            Type = "Studio"
                        },
                        new
                        {
                            Id = 11,
                            ApartmentId = 2,
                            Floor = 2,
                            IsAvailable = true,
                            Number = "202",
                            Type = "1 Bedroom"
                        },
                        new
                        {
                            Id = 12,
                            ApartmentId = 3,
                            Floor = 2,
                            IsAvailable = true,
                            Number = "203",
                            Type = "2 Bedroom"
                        },
                        new
                        {
                            Id = 13,
                            ApartmentId = 1,
                            Floor = 2,
                            IsAvailable = true,
                            Number = "204",
                            Type = "Studio"
                        },
                        new
                        {
                            Id = 14,
                            ApartmentId = 2,
                            Floor = 2,
                            IsAvailable = true,
                            Number = "205",
                            Type = "1 Bedroom"
                        },
                        new
                        {
                            Id = 15,
                            ApartmentId = 3,
                            Floor = 2,
                            IsAvailable = true,
                            Number = "206",
                            Type = "2 Bedroom"
                        },
                        new
                        {
                            Id = 16,
                            ApartmentId = 1,
                            Floor = 3,
                            IsAvailable = true,
                            Number = "301",
                            Type = "Studio"
                        },
                        new
                        {
                            Id = 17,
                            ApartmentId = 2,
                            Floor = 3,
                            IsAvailable = true,
                            Number = "302",
                            Type = "1 Bedroom"
                        },
                        new
                        {
                            Id = 18,
                            ApartmentId = 3,
                            Floor = 3,
                            IsAvailable = true,
                            Number = "303",
                            Type = "2 Bedroom"
                        },
                        new
                        {
                            Id = 19,
                            ApartmentId = 1,
                            Floor = 3,
                            IsAvailable = true,
                            Number = "304",
                            Type = "Studio"
                        },
                        new
                        {
                            Id = 20,
                            ApartmentId = 2,
                            Floor = 3,
                            IsAvailable = true,
                            Number = "305",
                            Type = "1 Bedroom"
                        },
                        new
                        {
                            Id = 21,
                            ApartmentId = 3,
                            Floor = 3,
                            IsAvailable = true,
                            Number = "306",
                            Type = "2 Bedroom"
                        },
                        new
                        {
                            Id = 22,
                            ApartmentId = 1,
                            Floor = 4,
                            IsAvailable = true,
                            Number = "401",
                            Type = "Studio"
                        },
                        new
                        {
                            Id = 23,
                            ApartmentId = 2,
                            Floor = 4,
                            IsAvailable = true,
                            Number = "402",
                            Type = "1 Bedroom"
                        },
                        new
                        {
                            Id = 24,
                            ApartmentId = 3,
                            Floor = 4,
                            IsAvailable = true,
                            Number = "403",
                            Type = "2 Bedroom"
                        },
                        new
                        {
                            Id = 25,
                            ApartmentId = 1,
                            Floor = 4,
                            IsAvailable = true,
                            Number = "404",
                            Type = "Studio"
                        },
                        new
                        {
                            Id = 26,
                            ApartmentId = 2,
                            Floor = 4,
                            IsAvailable = true,
                            Number = "405",
                            Type = "1 Bedroom"
                        },
                        new
                        {
                            Id = 27,
                            ApartmentId = 3,
                            Floor = 4,
                            IsAvailable = true,
                            Number = "406",
                            Type = "2 Bedroom"
                        },
                        new
                        {
                            Id = 28,
                            ApartmentId = 1,
                            Floor = 5,
                            IsAvailable = true,
                            Number = "501",
                            Type = "Studio"
                        },
                        new
                        {
                            Id = 29,
                            ApartmentId = 2,
                            Floor = 5,
                            IsAvailable = true,
                            Number = "502",
                            Type = "1 Bedroom"
                        },
                        new
                        {
                            Id = 30,
                            ApartmentId = 3,
                            Floor = 5,
                            IsAvailable = true,
                            Number = "503",
                            Type = "2 Bedroom"
                        },
                        new
                        {
                            Id = 31,
                            ApartmentId = 1,
                            Floor = 5,
                            IsAvailable = true,
                            Number = "504",
                            Type = "Studio"
                        },
                        new
                        {
                            Id = 32,
                            ApartmentId = 2,
                            Floor = 5,
                            IsAvailable = true,
                            Number = "505",
                            Type = "1 Bedroom"
                        },
                        new
                        {
                            Id = 33,
                            ApartmentId = 3,
                            Floor = 5,
                            IsAvailable = true,
                            Number = "506",
                            Type = "2 Bedroom"
                        },
                        new
                        {
                            Id = 34,
                            ApartmentId = 1,
                            Floor = 6,
                            IsAvailable = true,
                            Number = "601",
                            Type = "Studio"
                        },
                        new
                        {
                            Id = 35,
                            ApartmentId = 2,
                            Floor = 6,
                            IsAvailable = true,
                            Number = "602",
                            Type = "1 Bedroom"
                        },
                        new
                        {
                            Id = 36,
                            ApartmentId = 3,
                            Floor = 6,
                            IsAvailable = true,
                            Number = "603",
                            Type = "2 Bedroom"
                        },
                        new
                        {
                            Id = 37,
                            ApartmentId = 1,
                            Floor = 6,
                            IsAvailable = true,
                            Number = "604",
                            Type = "Studio"
                        },
                        new
                        {
                            Id = 38,
                            ApartmentId = 2,
                            Floor = 6,
                            IsAvailable = true,
                            Number = "605",
                            Type = "1 Bedroom"
                        },
                        new
                        {
                            Id = 39,
                            ApartmentId = 3,
                            Floor = 6,
                            IsAvailable = true,
                            Number = "606",
                            Type = "2 Bedroom"
                        });
                });

            modelBuilder.Entity("GolfViewApartments.API.Models.RoomRate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BoardType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("FirstOccupancy")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("RoomTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("SecondOccupancy")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("RoomTypeId");

                    b.ToTable("RoomRates");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BoardType = "Bed Only",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FirstOccupancy = 5000m,
                            RoomTypeId = 1,
                            SecondOccupancy = 7000m
                        },
                        new
                        {
                            Id = 2,
                            BoardType = "Bed and Breakfast",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FirstOccupancy = 5500m,
                            RoomTypeId = 1,
                            SecondOccupancy = 7500m
                        },
                        new
                        {
                            Id = 3,
                            BoardType = "Half Board",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FirstOccupancy = 6000m,
                            RoomTypeId = 1,
                            SecondOccupancy = 8000m
                        },
                        new
                        {
                            Id = 4,
                            BoardType = "Full Board",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FirstOccupancy = 6500m,
                            RoomTypeId = 1,
                            SecondOccupancy = 8500m
                        },
                        new
                        {
                            Id = 5,
                            BoardType = "Bed Only",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FirstOccupancy = 6000m,
                            RoomTypeId = 2,
                            SecondOccupancy = 8000m
                        },
                        new
                        {
                            Id = 6,
                            BoardType = "Bed and Breakfast",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FirstOccupancy = 6500m,
                            RoomTypeId = 2,
                            SecondOccupancy = 8500m
                        },
                        new
                        {
                            Id = 7,
                            BoardType = "Half Board",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FirstOccupancy = 7000m,
                            RoomTypeId = 2,
                            SecondOccupancy = 9000m
                        },
                        new
                        {
                            Id = 8,
                            BoardType = "Full Board",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FirstOccupancy = 7500m,
                            RoomTypeId = 2,
                            SecondOccupancy = 9500m
                        },
                        new
                        {
                            Id = 9,
                            BoardType = "Bed Only",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FirstOccupancy = 8000m,
                            RoomTypeId = 3,
                            SecondOccupancy = 10000m
                        },
                        new
                        {
                            Id = 10,
                            BoardType = "Bed and Breakfast",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FirstOccupancy = 8500m,
                            RoomTypeId = 3,
                            SecondOccupancy = 10500m
                        },
                        new
                        {
                            Id = 11,
                            BoardType = "Half Board",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FirstOccupancy = 9000m,
                            RoomTypeId = 3,
                            SecondOccupancy = 11000m
                        },
                        new
                        {
                            Id = 12,
                            BoardType = "Full Board",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FirstOccupancy = 9500m,
                            RoomTypeId = 3,
                            SecondOccupancy = 11500m
                        });
                });

            modelBuilder.Entity("GolfViewApartments.API.Models.RoomType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("IconClass")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("MaxOccupancy")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("RoomTypeEnum")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("RoomTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IconClass = "fa-solid fa-bed",
                            MaxOccupancy = 2,
                            Name = "Studio",
                            RoomTypeEnum = "Studio"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IconClass = "fa-solid fa-door-open",
                            MaxOccupancy = 2,
                            Name = "One Bedroom",
                            RoomTypeEnum = "OneBedroom"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IconClass = "fa-solid fa-house",
                            MaxOccupancy = 4,
                            Name = "Two Bedroom",
                            RoomTypeEnum = "TwoBedroom"
                        });
                });

            modelBuilder.Entity("GolfViewApartments.API.Models.Booking", b =>
                {
                    b.HasOne("GolfViewApartments.API.Models.Apartment", "Apartment")
                        .WithMany("Bookings")
                        .HasForeignKey("ApartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GolfViewApartments.API.Models.Customer", "Customer")
                        .WithMany("Bookings")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Apartment");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("GolfViewApartments.API.Models.Room", b =>
                {
                    b.HasOne("GolfViewApartments.API.Models.Apartment", "Apartment")
                        .WithMany("Rooms")
                        .HasForeignKey("ApartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Apartment");
                });

            modelBuilder.Entity("GolfViewApartments.API.Models.RoomRate", b =>
                {
                    b.HasOne("GolfViewApartments.API.Models.RoomType", "RoomType")
                        .WithMany("Rates")
                        .HasForeignKey("RoomTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RoomType");
                });

            modelBuilder.Entity("GolfViewApartments.API.Models.Apartment", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("Rooms");
                });

            modelBuilder.Entity("GolfViewApartments.API.Models.Customer", b =>
                {
                    b.Navigation("Bookings");
                });

            modelBuilder.Entity("GolfViewApartments.API.Models.RoomType", b =>
                {
                    b.Navigation("Rates");
                });
#pragma warning restore 612, 618
        }
    }
}
